services:
  web-api:
    build:
      context: ./web-api
    ports:
      - "5001:5001"
    volumes:
      - app-data:/app/data
    environment:
      - ASPNETCORE_URLS=http://+:5001
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/app.db

  web-client:
    build:
      context: ./web-client
    ports:
      - "8080:80"

  caddy:
    image: caddy:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./web-server/:/etc/caddy/
      - ./web-client/:/usr/share/caddy/
    depends_on:
      - web-client
      - web-api
    environment:
      - CADDY_TLS_INTERNAL=1

volumes:
  app-data: