services:
  web-api:
    build:
      context: ./web-api
    ports:
      - "5000:5000"
    volumes:
      - app-data:/app/data
    environment:
      - ASPNETCORE_URLS=http://+:5000      
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/cache.db

  web-ui:
    build:
      context: ./web-ui
    ports:
      - "8080:80"

  caddy:
    image: caddy:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./web-server/:/etc/caddy/
      - ./web-ui/:/usr/share/caddy/
    depends_on:
      - web-ui
      - web-api

volumes:
  app-data: